# Generated by Django 3.1.1 on 2020-09-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200924_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubecredentials',
            name='state',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
