# Generated by Django 3.1.1 on 2020-10-06 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='video',
        ),
        migrations.CreateModel(
            name='TagVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.tag')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
            options={
                'unique_together': {('video', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='ChannelSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.channel')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.source')),
            ],
            options={
                'unique_together': {('source', 'channel')},
            },
        ),
    ]
