# Generated by Django 3.1.1 on 2020-10-11 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelsource',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cs_channel', to='videos.channel'),
        ),
        migrations.AlterField(
            model_name='tagvideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tv_videos', to='videos.video'),
        ),
        migrations.AlterField(
            model_name='usermark',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='um_videos', to='videos.video'),
        ),
        migrations.AlterUniqueTogether(
            name='usermark',
            unique_together={('video', 'user')},
        ),
    ]
