# Generated by Django 3.1.1 on 2020-09-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermark',
            name='description_quality',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usermark',
            name='information_quality',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usermark',
            name='medical_practice_quality',
            field=models.IntegerField(null=True),
        ),
    ]
