# Generated by Django 3.1.1 on 2020-10-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20201022_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermark',
            name='description_quality',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usermark',
            name='information_quality',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usermark',
            name='medical_practice_quality',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usermark',
            name='practical_usage_availability',
            field=models.FloatField(default=0, null=True),
        ),
    ]
