# Generated by Django 3.1.1 on 2020-10-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20201006_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Checked'), (1, 'Checked')], default=0),
        ),
    ]
