# Generated by Django 3.1.2 on 2020-10-31 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20201022_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
