# Generated by Django 3.1.1 on 2020-10-11 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0001_initial'),
        ('videos', '0003_auto_20201011_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelsource',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cs_sources', to='filters.source'),
        ),
        migrations.AlterField(
            model_name='tagvideo',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tv_tags', to='filters.tag'),
        ),
    ]
