# Generated by Django 3.1.1 on 2020-09-27 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20200927_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='youtube_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='videos.youtubedata'),
        ),
        migrations.AlterField(
            model_name='youtubedata',
            name='video_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
