# Generated by Django 3.1.1 on 2020-10-06 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20201006_2038'),
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processvideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pv_videos', to='videos.video'),
        ),
    ]
