# Generated by Django 3.1.1 on 2020-09-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='search_data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
