# Generated by Django 3.1.1 on 2020-09-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_process_search_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='invalid_msg',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='next_process',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='prev_process',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
