# Generated by Django 2.2 on 2019-06-07 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etag', models.CharField(max_length=256)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('channel_id', models.CharField(max_length=64)),
                ('title', models.TextField()),
                ('video_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('description', models.TextField()),
                ('channel_title', models.CharField(max_length=128)),
                ('preview_url', models.CharField(max_length=512)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_count', models.IntegerField(db_index=True, default=0)),
                ('data', models.CharField(max_length=512)),
                ('hash_data', models.CharField(db_index=True, max_length=64)),
                ('full_url', models.CharField(max_length=512)),
                ('region', models.CharField(max_length=16)),
                ('etag', models.CharField(max_length=256)),
                ('next_page', models.CharField(blank=True, max_length=64, null=True)),
                ('prev_page', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestLinkConn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube_media.Links')),
                ('request_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube_media.RequestData')),
            ],
        ),
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube_media.Links')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
