# Generated by Django 2.2 on 2019-06-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdata',
            name='curr_page',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='prev_page',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
